name: Test SSM

on:
  workflow_dispatch:     

permissions:
  id-token: write

jobs:
  test-ssm-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::719709800508:role/test_GitHubOIDC_GlueSSMRole
          aws-region: us-east-1

      - name: Call SSM API
        run: aws ssm describe-instance-information

      - name: Test SSM SendCommand
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=i-0ac0b7b9e151c66df" \
            --parameters '{"commands":["echo Hello from GitHub Action!"]}' \
            --region us-east-1
